export const CHANGE_OFFICIAL_RANK_LIST = "rank/CHANGE_OFFICIAL_RANK_LIST";

export const CHANGE_GLOBAL_RANK_LIST = "rank/CHANGE_GLOBAL_RANK_LIST";

export const CHANGE_RANK_LOADING = "rank/CHANGE_RANK_LOADING";
